version: '3'

services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/usr/share/nginx/html"
    depends_on:
      - tedsearch_app

  tedsearch_app:
    image: tedsearchimg

  memcached:
    image: memcached

      