version: "3"

services: 
  jenkins: 
    build: ./
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "jenkins_home:/var/jenkins_home"
  
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    ports:
      - '80:80'
      - '23:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_logs:
  gitlab_data: